import "../globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";
import Image from "next/image";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const sessionCookie = cookieStore.get("session");
  let role = null;
  if (sessionCookie) {
    const session = JSON.parse(sessionCookie.value);
    if (
      session &&
      (session.role === "admin" ||
        session.role === "writer" ||
        session.role === "reader")
    ) {
      role = session.role;
    }
  }
  return (
    <html lang="en">
      <body>
        <header className="header-container">
          <div className="col-md-3 mb-2 mb-md-0 logo">
            <Link
              href="/"
              className="d-inline-flex link-body-emphasis text-decoration-none"
            >
              <Image
                src="/images/news-site.jpg"
                alt="My Photo"
                fill
                className="image"
              />
            </Link>
          </div>
          {!role && (
            <div className="col-md-3 text-end">
              <button type="button" className="btn btn-outline-primary me-2">
                <Link href="/login" className="link_first">
                  Login
                </Link>
              </button>
              <button type="button" className="btn btn-primary">
                <Link href="/signup" className="link_second">
                  Sign-up
                </Link>
              </button>
            </div>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}
